#ifndef ENUM_ERRCD_H_HEADER_INCLUDED_AF098088
#define ENUM_ERRCD_H_HEADER_INCLUDED_AF098088

//##ModelId=50ED3902017A
enum ENUM_ERRCD { 
    // 成功
    OK = 0, 
    SPACE_MANAGER_ALREADY_INIT , 
    // 内存分配超出限制
    SPACE_MANAGER_ALLOC_EXCEED_LIMIT = -19999, 
    // 内存分配超出限制
    SPACE_MANAGER_ALLOC_NOT, 
    // 空间管理初始化失败
    SPACE_MANAGER_INIT_FAIL ,
	// 堆栈无数据
	SPACE_MANAGER_LIFO_NO_ITEM,
	// 堆栈满
	SPACE_MANAGER_FILO_MAX_ITEM,
	// 堆栈未初始化
	SPACE_MANAGER_FILO_NOT_INIT,
	// 内存还没有初始化
    SPACE_MANAGER_NOT_INIT , 
    // 要释放的空间与此空间步匹配
    SPACE_MANAGER_FREE_BLOCK_NOT_MATCH,
    // 要释放的空间还没有分配
    SPACE_MANAGER_FREE_POINTER_NOT_ALLOC,
	// 空间不够分配
	SPACE_MANAGER_NOT_ENOUGH,
};



#endif /* ENUM_ERRCD_H_HEADER_INCLUDED_AF098088 */
