#ifndef SHAREMEMORY_ERRORCD_H_20120807
#define SHAREMEMORY_ERRORCD_H_20120807


enum ERRCD_OF_SHAREMEMEORY
{
	OK =0,
	SHM_SHMGET=1000,
	SHM_SHMCTL,
	SHM_GETLOCATION,
	SHM_SHMAT,
	SHM_NOT_INIT,
	SHM_NOT_ENOUGH_SPACE,
	SHM_SHM_ALREADY_ATTACHED,

	SHM_FILO_NOT_ENOUGH_SPACE = 2000,
	SHM_FILO_NO_ITEM,
	SHM_FILO_MAX_ITEM,

	SHM_FIFO_NOT_INIT = 3000,
	SHM_FIFO_NOT_ENOUGH_SPACE,
	SHM_FIFO_NO_ITEM,
	SHM_FIFO_ERROR_DATA,


	SHM_DATA_NOT_ALLOCATE = 4000,
	SHM_DATA_REUSED_MORE,

	SHM_USER_DATA_NOT_ALLOCATE = 5000,


};



#endif

